// <auto-generated />
using LifeProtectedInc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LifeProtectedInc.Migrations
{
    [DbContext(typeof(LifeContext))]
    partial class LifeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LifeProtectedInc.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nchar(2)")
                        .HasMaxLength(2);

                    b.Property<int>("StaffMemberID");

                    b.Property<int>("SupervisorID");

                    b.HasKey("ClientID");

                    b.HasIndex("StaffMemberID");

                    b.HasIndex("SupervisorID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LifeProtectedInc.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ProductAmount")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ProductNo");

                    b.HasKey("InventoryID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("LifeProtectedInc.Models.StaffMember", b =>
                {
                    b.Property<int>("StaffMemberID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.HasKey("StaffMemberID");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("LifeProtectedInc.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("InventoryID");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.HasKey("SupervisorID");

                    b.HasIndex("InventoryID");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("LifeProtectedInc.Models.Client", b =>
                {
                    b.HasOne("LifeProtectedInc.Models.StaffMember", "StaffMember")
                        .WithMany("Clients")
                        .HasForeignKey("StaffMemberID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LifeProtectedInc.Models.Supervisor", "Supervisor")
                        .WithMany("Clients")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LifeProtectedInc.Models.Supervisor", b =>
                {
                    b.HasOne("LifeProtectedInc.Models.Inventory", "Inventory")
                        .WithMany("Supervisors")
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
